# Generated by Django 4.1 on 2022-08-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='statususer',
        ),
    ]
