# Generated by Django 4.0.6 on 2022-08-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_post_comment_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
