# Generated by Django 4.1 on 2022-08-15 11:05

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_booking_statususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='statususer',
            field=models.IntegerField(choices=[(0, 'Не забронировано'), (1, 'Забронировано')], default=1, verbose_name=hotel.models.Room),
        ),
    ]
